### ISSUE TITLE
[Feature Request] Enable add_keys option to add a value of other columns

### ISSUE THREAD

**Issue by ysk24ok** [civitaspo/embulk-filter-json_key#8]
For example, when we have input.tsv as follows,

```tsv
id	json_info
1	{"age":23,"occupation":"doctor"}
2	{"age":34,"occupation":"pilot"}
```

by specifying the column name you want to add at `value` key with `from_other_columns: true`,

```yml
filters:
  - type: json_key
    column: json_info
    add_keys:
      - {key: name, value: id, from_other_columns: true}
```

expected output will be like this.

```tsv
id	json_info
1	{"age":23,"occupation":"doctor","id":1}
2	{"age":34,"occupation":"pilot","id":2}
```

If this feature request is a reasonable one, I will try sending a PR for this.
